# Generated by Django 5.0.4 on 2026-02-26 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_initial'),
        ('referees', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned for Revision')], default='draft', max_length=20)),
                ('home_score', models.PositiveIntegerField()),
                ('away_score', models.PositiveIntegerField()),
                ('home_yellow_cards', models.PositiveIntegerField(default=0)),
                ('away_yellow_cards', models.PositiveIntegerField(default=0)),
                ('home_red_cards', models.PositiveIntegerField(default=0)),
                ('away_red_cards', models.PositiveIntegerField(default=0)),
                ('match_duration', models.PositiveIntegerField(default=90, help_text='Actual minutes played')),
                ('added_time_ht', models.PositiveIntegerField(default=0, help_text='Added time 1st half (mins)')),
                ('added_time_ft', models.PositiveIntegerField(default=0, help_text='Added time 2nd half (mins)')),
                ('pitch_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('referee_notes', models.TextField(blank=True, help_text='Incidents, injuries, misconduct details')),
                ('is_abandoned', models.BooleanField(default=False)),
                ('abandonment_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_report', to='competitions.fixture')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_reports', to='referees.refereeprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Report',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('yellow', 'Yellow Card'), ('red', 'Red Card'), ('sub_on', 'Substitution On'), ('sub_off', 'Substitution Off'), ('injury', 'Injury'), ('penalty', 'Penalty Goal'), ('og', 'Own Goal')], max_length=20)),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.matchreport')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='SquadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved by Referee'), ('rejected', 'Rejected — Needs Changes')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='competitions.fixture')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squads_reviewed', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_submissions', to='teams.team')),
            ],
            options={
                'verbose_name': 'Squad Submission',
                'unique_together': {('fixture', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=True)),
                ('shirt_number', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_players', to='matches.squadsubmission')),
            ],
            options={
                'ordering': ['-is_starter', 'shirt_number'],
                'unique_together': {('submission', 'player')},
            },
        ),
    ]
