# Generated by Django 6.0.2 on 2026-03-02 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_remove_countyregistration_participation_fee_and_more'),
        ('matches', '0001_initial'),
        ('teams', '0007_team_away_gk_colour_team_away_kit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow', 'Yellow Card'), ('red', 'Red Card'), ('second_yellow', 'Second Yellow (Red)'), ('sub_on', 'Substitution On'), ('sub_off', 'Substitution Off'), ('injury', 'Injury'), ('penalty', 'Penalty Goal'), ('penalty_miss', 'Penalty Missed'), ('og', 'Own Goal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_started', models.PositiveIntegerField(default=0)),
                ('matches_sub', models.PositiveIntegerField(default=0, help_text='Appearances as substitute')),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('penalties_scored', models.PositiveIntegerField(default=0)),
                ('penalties_missed', models.PositiveIntegerField(default=0)),
                ('own_goals', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0, help_text='Matches where team conceded 0 goals (GK only)')),
                ('goals_conceded', models.PositiveIntegerField(default=0, help_text='Goals conceded while playing (GK only)')),
                ('goal_contributions', models.PositiveIntegerField(default=0, help_text='Goals + Assists')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='competitions.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='teams.team')),
            ],
            options={
                'verbose_name': 'Player Statistics',
                'verbose_name_plural': 'Player Statistics',
                'ordering': ['-goals', '-assists', '-matches_played'],
                'unique_together': {('player', 'competition')},
            },
        ),
    ]
