# Generated by Django 6.0.2 on 2026-03-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matchevent_event_type_alter_matchevent_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadsubmission',
            name='formation',
            field=models.CharField(blank=True, default='', help_text='Playing formation / units (e.g. 4-3-3, 4-4-2)', max_length=20),
        ),
        migrations.AddField(
            model_name='squadsubmission',
            name='kit_choice',
            field=models.CharField(choices=[('home', 'Home Kit'), ('away', 'Away Kit'), ('third', 'Third Kit')], default='home', help_text='Which kit the team will wear', max_length=10),
        ),
    ]
