# Generated by Django 6.0.2 on 2026-03-14 05:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_squadsubmission_formation_squadsubmission_kit_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='away_sets',
            field=models.PositiveIntegerField(default=0, help_text='Sets/periods won by away team'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='away_suspensions',
            field=models.PositiveIntegerField(default=0, help_text='2-minute suspensions (handball)'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='home_sets',
            field=models.PositiveIntegerField(default=0, help_text='Sets/periods won by home team'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='home_suspensions',
            field=models.PositiveIntegerField(default=0, help_text='2-minute suspensions (handball)'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='overtime_periods',
            field=models.PositiveIntegerField(default=0, help_text='Number of overtime periods played (basketball)'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='overtime_played',
            field=models.BooleanField(default=False, help_text='Was overtime/extra time played?'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow', 'Yellow Card'), ('red', 'Red Card'), ('second_yellow', 'Second Yellow (Red)'), ('sub_on', 'Substitution On'), ('sub_off', 'Substitution Off'), ('injury', 'Injury'), ('penalty', 'Penalty Goal'), ('penalty_miss', 'Penalty Missed'), ('og', 'Own Goal'), ('expulsion', 'Expulsion'), ('timeout', 'Timeout'), ('one_pointer', '1-Point Shot'), ('two_pointer', '2-Point Field Goal'), ('three_pointer', '3-Point Field Goal'), ('free_throw', 'Free Throw Made'), ('free_throw_miss', 'Free Throw Missed'), ('foul', 'Personal Foul'), ('tech_foul', 'Technical Foul'), ('unsportsmanlike', 'Unsportsmanlike Foul'), ('disqualifying', 'Disqualifying Foul'), ('seven_m_goal', '7m Throw Goal'), ('seven_m_miss', '7m Throw Missed'), ('two_min', '2-Minute Suspension'), ('blue_card', 'Blue Card (Report)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.CreateModel(
            name='PeriodScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(help_text='1-based period number (set, quarter, half)')),
                ('period_label', models.CharField(blank=True, help_text='e.g. Set 1, Q1, 1st Half, OT1', max_length=30)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('is_overtime', models.BooleanField(default=False, help_text='Whether this is an overtime/extra period')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_scores', to='matches.matchreport')),
            ],
            options={
                'ordering': ['period_number'],
                'unique_together': {('report', 'period_number')},
            },
        ),
    ]
