# Generated by Django 6.0.2 on 2026-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matchreport_appointment_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadsubmission',
            name='formation',
            field=models.CharField(blank=True, default='', help_text='Playing formation (e.g. 4-3-3, 4-4-2) — applies to football', max_length=20),
        ),
    ]
