# Generated by Django 6.0.2 on 2026-03-20 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_competition_sport_type'),
        ('matches', '0006_alter_squadsubmission_formation'),
        ('teams', '0024_alter_countydiscipline_sport_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadsubmission',
            options={'verbose_name': 'Team List', 'verbose_name_plural': 'Team Lists'},
        ),
        migrations.CreateModel(
            name='SubstitutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(help_text='Match minute when the substitution is requested')),
                ('sub_type', models.CharField(choices=[('normal', 'Normal Substitution'), ('concussion', 'Concussion Substitution')], default='normal', max_length=12)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved by 4th Official'), ('executed', 'Executed (Players Swapped)'), ('denied', 'Denied')], default='requested', max_length=12)),
                ('sub_window', models.PositiveIntegerField(blank=True, help_text='Substitution window number (soccer: 1-3). Null for sports with unlimited windows.', null=True)),
                ('grants_opponent_extra', models.BooleanField(default=False, help_text='If True, this concussion sub awarded the opponent an additional substitution.')),
                ('reason', models.TextField(blank=True, help_text='Reason for substitution (required for concussion subs).')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='4th official (normal) or referee (concussion) who approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='competitions.fixture')),
                ('player_off', models.ForeignKey(help_text='Player leaving the field', on_delete=django.db.models.deletion.CASCADE, related_name='subbed_off_requests', to='teams.player')),
                ('player_on', models.ForeignKey(help_text='Player entering the field', on_delete=django.db.models.deletion.CASCADE, related_name='subbed_on_requests', to='teams.player')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Team manager / bench official who requested the substitution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_requests_made', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='teams.team')),
            ],
            options={
                'verbose_name': 'Substitution Request',
                'ordering': ['fixture', 'team', 'minute'],
            },
        ),
    ]
