# Generated by Django 6.0.2 on 2026-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_squadsubmission_options_substitutionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadsubmission',
            name='formation',
            field=models.CharField(blank=True, default='', help_text='Playing formation (e.g. 4-3-3, 4-4-2) - applies to football', max_length=20),
        ),
        migrations.AlterField(
            model_name='squadsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved by Referee'), ('rejected', 'Rejected - Needs Changes')], default='draft', max_length=20),
        ),
    ]
