# Generated by Django 6.0.2 on 2026-07-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_squadsubmission_formation_and_more'),
        ('teams', '0037_ligi_mashinani_pipeline_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='squadplayer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='squadplayer',
            name='county_player',
            field=models.ForeignKey(blank=True, help_text='Ward-level squad entry links to a CountyPlayer rather than a Player', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_squad_entries', to='teams.countyplayer'),
        ),
        migrations.AlterField(
            model_name='squadplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.player'),
        ),
        migrations.AlterField(
            model_name='squadplayer',
            name='shirt_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
