# Generated by Django 5.0.4 on 2026-02-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('registered', 'Registered'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('badge', models.ImageField(blank=True, null=True, upload_to='team_badges/')),
                ('home_colour', models.CharField(blank=True, help_text='Primary kit colour', max_length=50)),
                ('away_colour', models.CharField(blank=True, max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='competitions.competition')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CDM', 'Defensive Mid'), ('CM', 'Centre Mid'), ('AM', 'Attacking Mid'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('CF', 'Centre Forward'), ('ST', 'Striker')], max_length=10)),
                ('shirt_number', models.PositiveIntegerField()),
                ('id_number', models.CharField(help_text='Birth cert / National ID', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('suspended', 'Suspended'), ('injured', 'Injured')], default='eligible', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'ordering': ['team', 'shirt_number'],
                'unique_together': {('team', 'shirt_number')},
            },
        ),
    ]
