# Generated by Django 6.0.2 on 2026-02-26 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_certificate',
            field=models.ImageField(blank=True, help_text='Copy of Birth Certificate', null=True, upload_to='players/birth_certs/'),
        ),
        migrations.AddField(
            model_name='player',
            name='id_document',
            field=models.ImageField(blank=True, help_text='Copy of National ID', null=True, upload_to='players/ids/'),
        ),
        migrations.AddField(
            model_name='player',
            name='rejection_notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes on rejection'),
        ),
        migrations.AddField(
            model_name='player',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('fake_id', 'Fake / Invalid ID'), ('fake_birth_cert', 'Fake / Invalid Birth Certificate'), ('photo_mismatch', 'Photo Does Not Match'), ('age_outside', 'Outside Age Bracket (18-23)'), ('incomplete_docs', 'Incomplete Documents'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport-size photo', null=True, upload_to='players/photos/'),
        ),
    ]
