# Generated by Django 6.0.2 on 2026-02-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_birth_certificate_player_id_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id_number',
        ),
        migrations.AddField(
            model_name='player',
            name='birth_cert_number',
            field=models.CharField(blank=True, default='', help_text='Birth Certificate number', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='national_id_number',
            field=models.CharField(blank=True, default='', help_text='National ID number', max_length=20),
        ),
    ]
