# Generated by Django 6.0.2 on 2026-02-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_sport_type'),
        ('teams', '0003_remove_player_id_number_player_birth_cert_number_and_more'),
    ]

    operations = [
    ]
