# Generated by Django 6.0.2 on 2026-02-28 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_merge_20260227_1914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid (KSh)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='Payment verified by treasurer'),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='M-Pesa or receipt reference', max_length=100),
        ),
    ]
