# Generated by Django 6.0.2 on 2026-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_add_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='county_logo',
            field=models.ImageField(blank=True, help_text='County government logo', null=True, upload_to='county_logos/'),
        ),
    ]
