# Generated by Django 6.0.2 on 2026-03-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_county_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='away_gk_colour',
            field=models.CharField(blank=True, help_text='Away goalkeeper jersey colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='away_kit_image',
            field=models.ImageField(blank=True, help_text='Photo of away kit', null=True, upload_to='kits/away/'),
        ),
        migrations.AddField(
            model_name='team',
            name='away_outfield_colour',
            field=models.CharField(blank=True, help_text='Away outfield jersey colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='away_shorts_colour',
            field=models.CharField(blank=True, help_text='Away shorts colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='away_socks_colour',
            field=models.CharField(blank=True, help_text='Away socks colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='home_gk_colour',
            field=models.CharField(blank=True, help_text='Home goalkeeper jersey colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='home_kit_image',
            field=models.ImageField(blank=True, help_text='Photo of home kit', null=True, upload_to='kits/home/'),
        ),
        migrations.AddField(
            model_name='team',
            name='home_outfield_colour',
            field=models.CharField(blank=True, help_text='Home outfield jersey colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='home_shorts_colour',
            field=models.CharField(blank=True, help_text='Home shorts colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='home_socks_colour',
            field=models.CharField(blank=True, help_text='Home socks colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='third_gk_colour',
            field=models.CharField(blank=True, help_text='Third goalkeeper jersey colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='third_kit_image',
            field=models.ImageField(blank=True, help_text='Photo of third kit', null=True, upload_to='kits/third/'),
        ),
        migrations.AddField(
            model_name='team',
            name='third_outfield_colour',
            field=models.CharField(blank=True, help_text='Third outfield jersey colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='third_shorts_colour',
            field=models.CharField(blank=True, help_text='Third shorts colour', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='third_socks_colour',
            field=models.CharField(blank=True, help_text='Third socks colour', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_colour',
            field=models.CharField(blank=True, help_text='Primary kit colour (legacy)', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_type',
            field=models.CharField(choices=[('football_men', 'Football (Men)'), ('football_women', 'Football (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], default='football_men', help_text='Sport this team competes in', max_length=30),
        ),
    ]
