# Generated by Django 6.0.2 on 2026-03-04 06:11

import django.db.models.deletion
from django.db import migrations, models


def disable_foreign_key_checks(apps, schema_editor):
    """Disable foreign key checks for SQLite during migration"""
    if schema_editor.connection.vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("PRAGMA foreign_keys = OFF")


def enable_foreign_key_checks(apps, schema_editor):
    """Re-enable foreign key checks for SQLite after migration"""
    if schema_editor.connection.vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("PRAGMA foreign_keys = ON")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_away_gk_colour_team_away_kit_image_and_more'),
    ]

    operations = [
        migrations.RunPython(disable_foreign_key_checks, enable_foreign_key_checks),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='County name (e.g., Nairobi, Mombasa)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='County code (e.g., NAI, MSA)', max_length=10, unique=True)),
                ('capital', models.CharField(blank=True, help_text='County capital/headquarters', max_length=100)),
                ('sports_officer_name', models.CharField(blank=True, help_text='Sports officer full name', max_length=200)),
                ('sports_officer_email', models.EmailField(blank=True, help_text='Sports officer email address', max_length=254)),
                ('sports_officer_phone', models.CharField(blank=True, help_text='Sports officer phone number', max_length=20)),
                ('alt_contact_name', models.CharField(blank=True, help_text='Alternative contact name', max_length=200)),
                ('alt_contact_email', models.EmailField(blank=True, help_text='Alternative contact email', max_length=254)),
                ('alt_contact_phone', models.CharField(blank=True, help_text='Alternative contact phone', max_length=20)),
                ('office_address', models.TextField(blank=True, help_text='County sports office address')),
                ('is_active', models.BooleanField(default=True, help_text='County is active and participating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='county',
            field=models.ForeignKey(blank=True, null=True, help_text='County this team represents', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.county'),
        ),
        migrations.RunPython(enable_foreign_key_checks, disable_foreign_key_checks),
    ]
