# Generated by Django 6.0.2 on 2026-03-04 06:17

from django.db import migrations


def populate_counties(apps, schema_editor):
    """Populate the County model with all 47 Kenyan counties"""
    County = apps.get_model('teams', 'County')
    
    counties_data = [
        # Name, Code, Capital, Sports Officer Name, Sports Officer Email, Phone
        ("Baringo", "BAR", "Kabarnet", "John Kiplagat", "sports.baringo@gmail.com", "+254720123001"),
        ("Bomet", "BOT", "Bomet", "Mary Cherotich", "sportsoffice.bomet@gmail.com", "+254720123002"),
        ("Bungoma", "BUN", "Bungoma", "Peter Wanyonyi", "sports.bungoma@gmail.com", "+254720123003"),
        ("Busia", "BUS", "Busia", "Grace Awino", "busia.sports@gmail.com", "+254720123004"),
        ("Elgeyo-Marakwet", "EMW", "Iten", "Samuel Kiprotich", "sports.elgeyomarakwet@gmail.com", "+254720123005"),
        ("Embu", "EMB", "Embu", "Catherine Wanjiku", "embu.sports@gmail.com", "+254720123006"),
        ("Garissa", "GAR", "Garissa", "Ahmed Hassan", "garissa.sports@gmail.com", "+254720123007"),
        ("Homa Bay", "HOM", "Homa Bay", "Daniel Ochieng", "homabay.sports@gmail.com", "+254720123008"),
        ("Isiolo", "ISO", "Isiolo", "Fatuma Ali", "isiolo.sports@gmail.com", "+254720123009"),
        ("Kajiado", "KAJ", "Kajiado", "Joseph Sankale", "kajiado.sports@gmail.com", "+254720123010"),
        ("Kakamega", "KAK", "Kakamega", "Margaret Wanjala", "kakamega.sports@gmail.com", "+254720123011"),
        ("Kericho", "KER", "Kericho", "Timothy Kiprop", "kericho.sports@gmail.com", "+254720123012"),
        ("Kiambu", "KIA", "Kiambu", "Susan Wanjiru", "kiambu.sports@gmail.com", "+254720123013"),
        ("Kilifi", "KIL", "Kilifi", "Omar Salim", "kilifi.sports@gmail.com", "+254720123014"),
        ("Kirinyaga", "KIR", "Kerugoya", "Peter Mwangi", "kirinyaga.sports@gmail.com", "+254720123015"),
        ("Kisii", "KIS", "Kisii", "Grace Nyaboke", "kisii.sports@gmail.com", "+254720123016"),
        ("Kisumu", "KSM", "Kisumu", "Michael Otieno", "kisumu.sports@gmail.com", "+254720123017"),
        ("Kitui", "KIT", "Kitui", "Agnes Mutindi", "kitui.sports@gmail.com", "+254720123018"),
        ("Kwale", "KWA", "Kwale", "Hassan Mwalimu", "kwale.sports@gmail.com", "+254720123019"),
        ("Laikipia", "LAI", "Nanyuki", "David Kariuki", "laikipia.sports@gmail.com", "+254720123020"),
        ("Lamu", "LAM", "Lamu", "Amina Mohamed", "lamu.sports@gmail.com", "+254720123021"),
        ("Machakos", "MAC", "Machakos", "Francis Musyoka", "machakos.sports@gmail.com", "+254720123022"),
        ("Makueni", "MAK", "Wote", "Jane Kavuu", "makueni.sports@gmail.com", "+254720123023"),
        ("Mandera", "MAN", "Mandera", "Abdullahi Ibrahim", "mandera.sports@gmail.com", "+254720123024"),
        ("Marsabit", "MAR", "Marsabit", "Halima Galgalo", "marsabit.sports@gmail.com", "+254720123025"),
        ("Meru", "MER", "Meru", "Boniface Muthuri", "meru.sports@gmail.com", "+254720123026"),
        ("Migori", "MIG", "Migori", "Rose Awuor", "migori.sports@gmail.com", "+254720123027"),
        ("Mombasa", "MSA", "Mombasa", "Ali Rashid", "mombasa.sports@gmail.com", "+254720123028"),
        ("Murang'a", "MUR", "Murang'a", "James Githinji", "muranga.sports@gmail.com", "+254720123029"),
        ("Nairobi", "NAI", "Nairobi", "Sarah Njeri", "nairobi.sports@gmail.com", "+254720123030"),
        ("Nakuru", "NAK", "Nakuru", "Robert Kimani", "nakuru.sports@gmail.com", "+254720123031"),
        ("Nandi", "NAN", "Kapsabet", "Lydia Chebet", "nandi.sports@gmail.com", "+254720123032"),
        ("Narok", "NAR", "Narok", "Wilson Sankale", "narok.sports@gmail.com", "+254720123033"),
        ("Nyamira", "NYA", "Nyamira", "Esther Moraa", "nyamira.sports@gmail.com", "+254720123034"),
        ("Nyandarua", "NYN", "Ol Kalou", "Patrick Mwangi", "nyandarua.sports@gmail.com", "+254720123035"),
        ("Nyeri", "NYE", "Nyeri", "Ann Wambui", "nyeri.sports@gmail.com", "+254720123036"),
        ("Samburu", "SAM", "Maralal", "Jackson Lekalgitele", "samburu.sports@gmail.com", "+254720123037"),
        ("Siaya", "SIA", "Siaya", "Tom Odhiambo", "siaya.sports@gmail.com", "+254720123038"),
        ("Taita-Taveta", "TTA", "Voi", "Elizabeth Mwakio", "taitataveta.sports@gmail.com", "+254720123039"),
        ("Tana River", "TAN", "Hola", "Salim Juma", "tanariver.sports@gmail.com", "+254720123040"),
        ("Tharaka-Nithi", "THN", "Chuka", "Moses Kimathi", "tharakanithi.sports@gmail.com", "+254720123041"),
        ("Trans Nzoia", "TNZ", "Kitale", "Alice Wanjala", "transnzoia.sports@gmail.com", "+254720123042"),
        ("Turkana", "TUR", "Lodwar", "Paul Ekale", "turkana.sports@gmail.com", "+254720123043"),
        ("Uasin Gishu", "UAS", "Eldoret", "Mercy Chepkemoi", "uasingishu.sports@gmail.com", "+254720123044"),
        ("Vihiga", "VIH", "Vihiga", "Nancy Shiundu", "vihiga.sports@gmail.com", "+254720123045"),
        ("Wajir", "WAJ", "Wajir", "Amina Abdi", "wajir.sports@gmail.com", "+254720123046"),
        ("West Pokot", "WPK", "Kapenguria", "Simon Pkosing", "westpokot.sports@gmail.com", "+254720123047"),
    ]

    for name, code, capital, officer_name, officer_email, phone in counties_data:
        County.objects.get_or_create(
            name=name,
            defaults={
                'code': code,
                'capital': capital,
                'sports_officer_name': officer_name,
                'sports_officer_email': officer_email,
                'sports_officer_phone': phone,
                'office_address': f"{capital} County Sports Office",
                'is_active': True,
            }
        )
    print(f"✅ Created {County.objects.count()} counties")


def migrate_team_counties(apps, schema_editor):
    """Map existing Team.county string values to County foreign keys"""
    Team = apps.get_model('teams', 'Team')
    County = apps.get_model('teams', 'County')
    
    # County name mappings for common variations
    county_mappings = {
        # Existing string -> County name
        "WAJIR COUNTY": "Wajir",
        "NAIROBI COUNTY": "Nairobi", 
        "MOMBASA COUNTY": "Mombasa",
        "KISUMU COUNTY": "Kisumu",
        "NAKURU COUNTY": "Nakuru",
        "ELDORET": "Uasin Gishu",
        "KIAMBU COUNTY": "Kiambu",
        "MACHAKOS COUNTY": "Machakos",
        "MAKUENI COUNTY": "Makueni",
        "KITUI COUNTY": "Kitui",
        "EMBU COUNTY": "Embu",
        "MERU COUNTY": "Meru",
        "NYERI COUNTY": "Nyeri",
        "MURANG'A COUNTY": "Murang'a", 
        "KIRINYAGA COUNTY": "Kirinyaga",
        "NYANDARUA COUNTY": "Nyandarua",
        "LAIKIPIA COUNTY": "Laikipia",
        "SAMBURU COUNTY": "Samburu",
        "MARSABIT COUNTY": "Marsabit",
        "ISIOLO COUNTY": "Isiolo",
        "GARISSA COUNTY": "Garissa",
        "WAJIR": "Wajir",
        "MANDERA COUNTY": "Mandera", 
        "LAMU COUNTY": "Lamu",
        "TANA RIVER COUNTY": "Tana River",
        "KILIFI COUNTY": "Kilifi",
        "KWALE COUNTY": "Kwale",
        "TAITA TAVETA COUNTY": "Taita-Taveta",
        "KAKAMEGA COUNTY": "Kakamega",
        "VIHIGA COUNTY": "Vihiga",
        "BUNGOMA COUNTY": "Bungoma",
        "BUSIA COUNTY": "Busia",
        "SIAYA COUNTY": "Siaya",
        "KISUMU": "Kisumu",
        "HOMA BAY COUNTY": "Homa Bay",
        "MIGORI COUNTY": "Migori",
        "KISII COUNTY": "Kisii",
        "NYAMIRA COUNTY": "Nyamira",
        "BOMET COUNTY": "Bomet",
        "KERICHO COUNTY": "Kericho",
        "NANDI COUNTY": "Nandi",
        "UASIN GISHU COUNTY": "Uasin Gishu",
        "ELGEYO MARAKWET COUNTY": "Elgeyo-Marakwet",
        "WEST POKOT COUNTY": "West Pokot",
        "TURKANA COUNTY": "Turkana",
        "TRANS NZOIA COUNTY": "Trans Nzoia",
        "BARINGO COUNTY": "Baringo",
        "KAJIADO COUNTY": "Kajiado",
        "NAROK COUNTY": "Narok",
        "THARAKA NITHI COUNTY": "Tharaka-Nithi",
        # Add variations without "COUNTY" suffix
        "WAJIR": "Wajir",
        "NAIROBI": "Nairobi",
        "MOMBASA": "Mombasa",
        "KISUMU": "Kisumu",
        "NAKURU": "Nakuru",
        "KIAMBU": "Kiambu",
        "MACHAKOS": "Machakos",
        "MAKUENI": "Makueni",
        "KITUI": "Kitui",
        "EMBU": "Embu",
        "MERU": "Meru",
        "NYERI": "Nyeri",
        "MURANG'A": "Murang'a",
        "MURANGA": "Murang'a",
        "KIRINYAGA": "Kirinyaga",
        "NYANDARUA": "Nyandarua",
        "LAIKIPIA": "Laikipia",
        "SAMBURU": "Samburu",
        "MARSABIT": "Marsabit",
        "ISIOLO": "Isiolo",
        "GARISSA": "Garissa",
        "MANDERA": "Mandera",
        "LAMU": "Lamu",
        "TANA RIVER": "Tana River",
        "KILIFI": "Kilifi",
        "KWALE": "Kwale",
        "TAITA TAVETA": "Taita-Taveta",
        "KAKAMEGA": "Kakamega",
        "VIHIGA": "Vihiga", 
        "BUNGOMA": "Bungoma",
        "BUSIA": "Busia",
        "SIAYA": "Siaya",
        "HOMA BAY": "Homa Bay",
        "MIGORI": "Migori",
        "KISII": "Kisii",
        "NYAMIRA": "Nyamira",
        "BOMET": "Bomet",
        "KERICHO": "Kericho",
        "NANDI": "Nandi",
        "UASIN GISHU": "Uasin Gishu", 
        "ELGEYO MARAKWET": "Elgeyo-Marakwet",
        "WEST POKOT": "West Pokot",
        "TURKANA": "Turkana",
        "TRANS NZOIA": "Trans Nzoia",
        "BARINGO": "Baringo",
        "KAJIADO": "Kajiado",
        "NAROK": "Narok",
        "THARAKA NITHI": "Tharaka-Nithi",
    }
    
    # Get all teams and try to map their county values
    migrated_count = 0
    failed_mappings = []
    
    # First, let's use raw SQL to check what county values we have
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT DISTINCT county FROM teams_team WHERE county IS NOT NULL")
        existing_counties = [row[0] for row in cursor.fetchall()]
    
    print(f"Found existing county values: {existing_counties}")
    
    for existing_county in existing_counties:
        if existing_county in county_mappings:
            county_name = county_mappings[existing_county]
            try:
                county_obj = County.objects.get(name=county_name)
                # Update teams with this county using raw SQL to avoid the FK constraint
                with connection.cursor() as cursor:
                    cursor.execute(
                        "UPDATE teams_team SET county_id = %s WHERE county = %s", 
                        [county_obj.id, existing_county]
                    )
                    updated_count = cursor.rowcount
                    migrated_count += updated_count
                    print(f"✅ Mapped '{existing_county}' -> '{county_name}' ({updated_count} teams)")
            except County.DoesNotExist:
                failed_mappings.append(f"'{existing_county}' -> '{county_name}' (County not found)")
        else:
            # Try fuzzy matching
            matched = False
            for county in County.objects.all():
                if county.name.upper() in existing_county.upper() or existing_county.upper() in county.name.upper():
                    with connection.cursor() as cursor:
                        cursor.execute(
                            "UPDATE teams_team SET county_id = %s WHERE county = %s", 
                            [county.id, existing_county]
                        )
                        updated_count = cursor.rowcount
                        migrated_count += updated_count
                        print(f"🔄 Fuzzy matched '{existing_county}' -> '{county.name}' ({updated_count} teams)")
                        matched = True
                        break
            if not matched:
                failed_mappings.append(f"'{existing_county}' (No mapping found)")
    
    print(f"✅ Migration complete: {migrated_count} teams migrated")
    if failed_mappings:
        print(f"⚠️  Failed mappings: {failed_mappings}")


def reverse_migrate_team_counties(apps, schema_editor):
    """Reverse migration - convert County FKs back to string county names"""
    Team = apps.get_model('teams', 'Team')
    County = apps.get_model('teams', 'County')
    
    # This is complex to reverse since we'd lose the original string format
    # For now, we'll just use the county names
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE teams_team 
            SET county = (
                SELECT name FROM teams_county 
                WHERE teams_county.id = teams_team.county_id
            )
            WHERE county_id IS NOT NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_county_alter_team_county'),
    ]

    operations = [
        migrations.RunPython(populate_counties, migrations.RunPython.noop),
        migrations.RunPython(migrate_team_counties, reverse_migrate_team_counties),
    ]
