# Generated by Django 6.0.2 on 2026-03-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_populate_counties_and_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='county',
            field=models.ForeignKey(help_text='County this team represents', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.county'),
        ),
    ]
