# Generated by Django 6.0.2 on 2026-03-05 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_make_county_non_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fifa_connect_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_connect_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifa_connect_checked_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_connect_id',
            field=models.CharField(blank=True, default='', help_text='FIFA Connect Player ID', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_connect_leagues',
            field=models.JSONField(blank=True, default=list, help_text='List of higher-level leagues found in FIFA Connect'),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_connect_notes',
            field=models.TextField(blank=True, default='', help_text='Notes from FIFA Connect check'),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_connect_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('pending', 'Pending Check'), ('clear', 'Clear — No Higher League'), ('flagged', 'Flagged — Higher League Found'), ('error', 'API Error')], default='not_checked', help_text='FIFA Connect higher-league check status', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='huduma_notes',
            field=models.TextField(blank=True, default='', help_text='Notes from Huduma verification'),
        ),
        migrations.AddField(
            model_name='player',
            name='huduma_reference',
            field=models.CharField(blank=True, default='', help_text='Huduma Kenya verification reference', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='huduma_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='not_checked', help_text='Huduma Kenya age verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='huduma_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='huduma_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huduma_verified_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('fake_id', 'Fake / Invalid ID'), ('fake_birth_cert', 'Fake / Invalid Birth Certificate'), ('photo_mismatch', 'Photo Does Not Match'), ('age_outside', 'Outside Age Bracket (18-23)'), ('incomplete_docs', 'Incomplete Documents'), ('fifa_connect_flagged', 'Flagged by FIFA Connect (Higher League)'), ('huduma_failed', 'Huduma Kenya Verification Failed'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='PlayerVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('document', 'Document Verification'), ('huduma', 'Huduma Kenya (Age)'), ('fifa_connect', 'FIFA Connect (League Check)'), ('clearance', 'Final Clearance')], max_length=20)),
                ('action', models.CharField(help_text="e.g. 'verified', 'rejected', 'flagged', 'cleared'", max_length=50)),
                ('result', models.CharField(help_text='Outcome of the action', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed data from the verification')),
                ('notes', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='teams.player')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
