# Generated by Django 6.0.2 on 2026-03-06 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_player_fifa_connect_checked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('football_men', 'Football (Men)'), ('football_women', 'Football (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball_men', 'Basketball 5x5 (Men)'), ('basketball_women', 'Basketball 5x5 (Women)'), ('basketball_3x3_men', 'Basketball 3x3 (Men)'), ('basketball_3x3_women', 'Basketball 3x3 (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball_men', 'Handball (Men)'), ('handball_women', 'Handball (Women)'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], max_length=30)),
            ],
            options={
                'ordering': ['sport_type'],
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_type',
            field=models.CharField(choices=[('football_men', 'Football (Men)'), ('football_women', 'Football (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball_men', 'Basketball 5x5 (Men)'), ('basketball_women', 'Basketball 5x5 (Women)'), ('basketball_3x3_men', 'Basketball 3x3 (Men)'), ('basketball_3x3_women', 'Basketball 3x3 (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball_men', 'Handball (Men)'), ('handball_women', 'Handball (Women)'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], default='football_men', help_text='Sport this team competes in', max_length=30),
        ),
        migrations.CreateModel(
            name='CountyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('national_id_number', models.CharField(help_text='National ID — unique across all counties and disciplines', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='county_players/photos/')),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='county_players/ids/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.countydiscipline')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CountyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita Taveta', 'Taita Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', "Murang'a"), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], help_text='Kenyan county (only one admin per county)', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_submitted', 'Payment Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_payment', max_length=20)),
                ('mpesa_reference', models.CharField(blank=True, default='', max_length=100)),
                ('bank_slip', models.FileField(blank=True, null=True, upload_to='county_reg/bank_slips/')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='county_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['county'],
            },
        ),
        migrations.AddField(
            model_name='countydiscipline',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='teams.countyregistration'),
        ),
        migrations.AlterUniqueTogether(
            name='countydiscipline',
            unique_together={('registration', 'sport_type')},
        ),
    ]
