# Generated by Django 6.0.2 on 2026-03-13 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_countydiscipline_alter_team_sport_type_countyplayer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countyplayer',
            name='birth_certificate',
            field=models.ImageField(blank=True, help_text='Copy of Birth Certificate (optional)', null=True, upload_to='county_players/birth_certs/'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='higher_league_details',
            field=models.TextField(blank=True, default='', help_text='Details of higher league / national team participation if flagged'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='higher_league_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('clear', 'Clear'), ('flagged', 'Flagged — Higher League / National Team')], default='not_checked', help_text='For non-football disciplines: check if player is in higher league or national team', max_length=20),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='huduma_number',
            field=models.CharField(blank=True, default='', help_text='Huduma Namba / Huduma Kenya number', max_length=30),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='huduma_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('verified', 'Verified'), ('failed', 'Failed')], default='not_checked', max_length=20),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='huduma_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, help_text='Jersey number', null=True),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Player position (where applicable)', max_length=10),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified / Approved'), ('rejected', 'Rejected'), ('resubmit', 'Requires Resubmission')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='id_document',
            field=models.ImageField(blank=True, help_text='Copy of National ID (required)', null=True, upload_to='county_players/ids/'),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport-size photo (required)', null=True, upload_to='county_players/photos/'),
        ),
        migrations.CreateModel(
            name='TechnicalBenchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('team_manager', 'Team Manager'), ('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('national_id_number', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='technical_bench/photos/')),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='technical_bench/ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_bench', to='teams.countydiscipline')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_bench_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['discipline', 'role'],
                'unique_together': {('discipline', 'role')},
            },
        ),
    ]
