# Generated by Django 6.0.2 on 2026-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_countyplayer_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyregistration',
            name='director_name',
            field=models.CharField(blank=True, default='', help_text='Full name of the Director of Sports for this county', max_length=200),
        ),
        migrations.AddField(
            model_name='countyregistration',
            name='director_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of the Director of Sports', max_length=20),
        ),
    ]
