# Generated by Django 6.0.2 on 2026-03-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_add_director_fields_to_county_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyplayer',
            name='iprs_photo',
            field=models.ImageField(blank=True, help_text='Passport photo returned from IPRS lookup (auto-populated)', null=True, upload_to='county_players/iprs_photos/'),
        ),
    ]
