# Generated by Django 6.0.2 on 2026-03-17 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_add_iprs_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='1 = Low potential, 5 = Outstanding')),
                ('notes', models.TextField(blank=True, default='', help_text='Scouting notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_entries', to='teams.countyplayer')),
                ('scout', models.ForeignKey(limit_choices_to={'role': 'scout'}, on_delete=django.db.models.deletion.CASCADE, related_name='scout_shortlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scout Shortlist Entry',
                'verbose_name_plural': 'Scout Shortlist Entries',
                'ordering': ['-updated_at'],
                'unique_together': {('scout', 'player')},
            },
        ),
    ]
