# Generated by Django 6.0.2 on 2026-03-17 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_scoutshortlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='alt_contact_phone',
            field=models.CharField(blank=True, help_text='Alternative contact phone', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='county',
            name='sports_officer_phone',
            field=models.CharField(blank=True, help_text='Sports officer phone number', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='countyregistration',
            name='director_phone',
            field=models.CharField(help_text='Phone number of the Director of Sports', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='technicalbenchmember',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
    ]
