# Generated by Django 6.0.2 on 2026-03-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_alter_county_alt_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyregistration',
            name='bank_reference',
            field=models.CharField(blank=True, default='', help_text='Bank payment/transfer reference code', max_length=100),
        ),
        migrations.AddField(
            model_name='countyregistration',
            name='mpesa_checkout_id',
            field=models.CharField(blank=True, default='', help_text='Daraja STK push CheckoutRequestID', max_length=100),
        ),
        migrations.AddField(
            model_name='countyregistration',
            name='mpesa_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number used for M-Pesa payment', max_length=13),
        ),
        migrations.AddField(
            model_name='countyregistration',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='mpesa or bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='countyregistration',
            name='bank_slip',
            field=models.FileField(blank=True, help_text='Bank deposit slip (image or PDF)', null=True, upload_to='county_reg/bank_slips/'),
        ),
        migrations.AlterField(
            model_name='countyregistration',
            name='mpesa_reference',
            field=models.CharField(blank=True, default='', help_text='M-Pesa transaction code from confirmation SMS', max_length=100),
        ),
    ]
