# Generated by Django 6.0.2 on 2026-03-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_countydelegationmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countydiscipline',
            options={'ordering': ['sub_county', 'sport_type']},
        ),
        migrations.AlterUniqueTogether(
            name='countydiscipline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='countydiscipline',
            name='sub_county',
            field=models.CharField(blank=True, default='', help_text='Sub-county or constituency that owns this discipline entry', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='source_discipline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_team', to='teams.countydiscipline'),
        ),
        migrations.AddField(
            model_name='team',
            name='sub_county',
            field=models.CharField(blank=True, default='', help_text='Sub-county or constituency this team represents', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='payment_confirmed',
            field=models.BooleanField(default=True, help_text='Registration cleared for competition participation'),
        ),
        migrations.AlterUniqueTogether(
            name='countydiscipline',
            unique_together={('registration', 'sport_type', 'sub_county')},
        ),
    ]
