# Generated by Django 6.0.2 on 2026-03-19 15:12

from django.db import migrations
from django.utils.text import slugify


def county_code_base(county_name):
    base = slugify(county_name or 'county').replace('-', '').upper()
    return (base or 'COUNTY')[:10]


def ensure_county(apps, county_name, sports_officer_name='', sports_officer_email='', sports_officer_phone=''):
    County = apps.get_model('teams', 'County')
    county = County.objects.filter(name__iexact=county_name).first()
    if county:
        updated = False
        if sports_officer_name and not county.sports_officer_name:
            county.sports_officer_name = sports_officer_name
            updated = True
        if sports_officer_email and not county.sports_officer_email:
            county.sports_officer_email = sports_officer_email
            updated = True
        if sports_officer_phone and not county.sports_officer_phone:
            county.sports_officer_phone = sports_officer_phone
            updated = True
        if updated:
            county.save(update_fields=['sports_officer_name', 'sports_officer_email', 'sports_officer_phone', 'updated_at'])
        return county

    code_base = county_code_base(county_name)
    code = code_base
    suffix = 1
    while County.objects.filter(code=code).exists():
        token = str(suffix)
        code = f"{code_base[:10 - len(token)]}{token}"
        suffix += 1

    return County.objects.create(
        name=county_name,
        code=code,
        sports_officer_name=sports_officer_name,
        sports_officer_email=sports_officer_email,
        sports_officer_phone=sports_officer_phone,
    )


def unique_team_name(Team, base_name, source_discipline_id, existing_pk=None):
    candidate = (base_name or 'County Team')[:200]
    suffix = 1
    while True:
        qs = Team.objects.filter(name=candidate)
        if existing_pk:
            qs = qs.exclude(pk=existing_pk)
        if not qs.exclude(source_discipline_id=source_discipline_id).exists():
            return candidate
        token = f' #{suffix}'
        candidate = f"{base_name[:200 - len(token)]}{token}"
        suffix += 1


def backfill_linked_teams(apps, schema_editor):
    CountyRegistration = apps.get_model('teams', 'CountyRegistration')
    CountyDiscipline = apps.get_model('teams', 'CountyDiscipline')
    Team = apps.get_model('teams', 'Team')

    sport_labels = dict(CountyDiscipline._meta.get_field('sport_type').choices)

    Team.objects.filter(payment_confirmed=False).update(payment_confirmed=True)

    for discipline in CountyDiscipline.objects.select_related('registration', 'registration__user').all():
        registration = discipline.registration
        county = ensure_county(
            apps,
            registration.county,
            sports_officer_name=registration.director_name,
            sports_officer_email=getattr(registration.user, 'email', ''),
            sports_officer_phone=registration.director_phone,
        )

        owner = discipline.sub_county or registration.county
        sport_label = sport_labels.get(discipline.sport_type, discipline.sport_type)
        team_name = unique_team_name(
            Team,
            f'{owner} {sport_label}'.strip(),
            discipline.pk,
        )

        team = Team.objects.filter(source_discipline_id=discipline.pk).first()
        if team is None:
            team = Team.objects.filter(
                county=county,
                sport_type=discipline.sport_type,
                sub_county=discipline.sub_county,
            ).order_by('pk').first()

        if team is None:
            Team.objects.create(
                name=team_name,
                county=county,
                sub_county=discipline.sub_county,
                sport_type=discipline.sport_type,
                source_discipline_id=discipline.pk,
                status='registered',
                payment_confirmed=True,
                payment_amount=0,
                contact_phone=registration.director_phone or getattr(registration.user, 'phone', '+254700000000'),
                contact_email=getattr(registration.user, 'email', ''),
            )
            continue

        team.name = unique_team_name(Team, f'{owner} {sport_label}'.strip(), discipline.pk, existing_pk=team.pk)
        team.county = county
        team.sub_county = discipline.sub_county
        team.sport_type = discipline.sport_type
        team.source_discipline_id = discipline.pk
        team.status = 'registered'
        team.payment_confirmed = True
        if team.payment_amount is None:
            team.payment_amount = 0
        if not team.contact_phone:
            team.contact_phone = registration.director_phone or getattr(registration.user, 'phone', '+254700000000')
        if not team.contact_email:
            team.contact_email = getattr(registration.user, 'email', '')
        team.save()

    for registration in CountyRegistration.objects.select_related('user').all():
        ensure_county(
            apps,
            registration.county,
            sports_officer_name=registration.director_name,
            sports_officer_email=getattr(registration.user, 'email', ''),
            sports_officer_phone=registration.director_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_alter_countydiscipline_options_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_linked_teams, migrations.RunPython.noop),
    ]