# Generated by Django 6.0.2 on 2026-03-20 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_countypayment_participation_fee'),
        ('teams', '0021_backfill_linked_subcounty_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(blank=True, max_length=30)),
                ('criteria_scores', models.JSONField(default=dict)),
                ('overall_rating', models.PositiveSmallIntegerField(help_text='Overall rating 1–10')),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('monitor', 'Continue Monitoring'), ('not_recommended', 'Not Recommended')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('minutes_observed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='competitions.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='teams.player')),
                ('scout', models.ForeignKey(limit_choices_to={'role': 'scout'}, on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scout', 'player', 'fixture')},
            },
        ),
    ]
