# Generated by Django 6.0.2 on 2026-03-20 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_add_scout_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyplayer',
            name='sub_county',
            field=models.CharField(blank=True, default='', help_text='Sub-county the player represents', max_length=100),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='ward',
            field=models.CharField(blank=True, default='', help_text='Ward within the sub-county', max_length=100),
        ),
        migrations.AlterField(
            model_name='countydelegationmember',
            name='national_id_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='national_id_number',
            field=models.CharField(help_text='National ID — unique across all counties and disciplines', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
        migrations.AlterField(
            model_name='countyregistration',
            name='mpesa_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number used for M-Pesa payment', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='national_id_number',
            field=models.CharField(blank=True, default='', help_text='National ID number', max_length=20, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
        migrations.AlterField(
            model_name='technicalbenchmember',
            name='national_id_number',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
    ]
