# Generated by Django 6.0.2 on 2026-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_scoutshortlistsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyplayer',
            name='doc_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='doc_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_checked', help_text='Step 1 — manual review of photo, ID document & birth certificate', max_length=20),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='doc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='higher_league_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='huduma_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='iprs_age_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='iprs_age_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('verified', 'Age Verified'), ('failed', 'Age Mismatch / Failed')], default='not_checked', help_text='Step 4 — verify age via IPRS (manual now, automated when API available)', max_length=20),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='iprs_age_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='higher_league_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('clear', 'Clear'), ('flagged', 'Flagged — Higher League / National Team')], default='not_checked', help_text='Check if player is registered in a higher league or national team', max_length=20),
        ),
    ]
