# Generated by Django 6.0.2 on 2026-03-26 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_sequential_verification_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countyplayer',
            name='director_approved',
            field=models.BooleanField(default=False, help_text='Final approval by Director of Sports'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='director_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_approved_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='director_disapproval_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for disapproval'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='director_disapproved',
            field=models.BooleanField(default=False, help_text='Disapproved by Director of Sports'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='director_locked',
            field=models.BooleanField(default=False, help_text='Locked by Director of Sports — no further edits except by Director'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='director_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
