# Generated by Django 6.0.2 on 2026-03-27 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_director_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyplayer',
            name='director_locked',
            field=models.BooleanField(default=False, help_text='Locked by Director of Sports - no further edits except by Director'),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='doc_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_checked', help_text='Step 1 - manual review of photo, ID document & birth certificate', max_length=20),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='higher_league_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('clear', 'Clear'), ('flagged', 'Flagged - Higher League / National Team')], default='not_checked', help_text='Check if player is registered in a higher league or national team', max_length=20),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='iprs_age_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('verified', 'Age Verified'), ('failed', 'Age Mismatch / Failed')], default='not_checked', help_text='Step 4 - verify age via IPRS (manual now, automated when API available)', max_length=20),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='national_id_number',
            field=models.CharField(help_text='National ID - unique across all counties and disciplines', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='fifa_connect_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('pending', 'Pending Check'), ('clear', 'Clear - No Higher League'), ('flagged', 'Flagged - Higher League Found'), ('error', 'API Error')], default='not_checked', help_text='FIFA Connect higher-league check status', max_length=20),
        ),
        migrations.AlterField(
            model_name='scoutreport',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(help_text='Overall rating 1 - 10'),
        ),
    ]
