# Generated by Django 6.0.2 on 2026-03-31 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_alter_countyplayer_director_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPlayerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Excel (.xlsx) file with player data', upload_to='bulk_uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('sport_type', models.CharField(choices=[('football_men', 'Soccer (Men)'), ('football_women', 'Soccer (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball_men', 'Basketball 5x5 (Men)'), ('basketball_women', 'Basketball 5x5 (Women)'), ('basketball_3x3_men', 'Basketball 3x3 (Men)'), ('basketball_3x3_women', 'Basketball 3x3 (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball_men', 'Handball (Men)'), ('handball_women', 'Handball (Women)'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], max_length=30)),
                ('sub_county', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Uploader notes')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads_reviewed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkPlayerUploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id_number', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('position', models.CharField(blank=True, default='', max_length=30)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ward', models.CharField(blank=True, default='', max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('county_player', models.ForeignKey(blank=True, help_text='CountyPlayer created from this row on approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_source', to='teams.countyplayer')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='teams.bulkplayerupload')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('upload', 'row_number')},
            },
        ),
    ]
