# Generated by Django 6.0.2 on 2026-03-31 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_bulkplayerupload_bulkplayeruploadrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='edit_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for editing this row (required on edit)'),
        ),
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_row_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Full name as per ID document', max_length=200),
        ),
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='ligi_mashinani_team',
            field=models.CharField(blank=True, default='', help_text='Team in Ligi Mashinani', max_length=200),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='ligi_mashinani_team',
            field=models.CharField(blank=True, default='', help_text='Team in Ligi Mashinani', max_length=200),
        ),
        migrations.AlterField(
            model_name='bulkplayerupload',
            name='file',
            field=models.FileField(help_text='Excel (.xlsx) or Word (.docx) file with player data', upload_to='bulk_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='countyplayer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
