# Generated by Django 6.0.2 on 2026-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_bulkplayeruploadrow_edit_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='age_value',
            field=models.PositiveIntegerField(blank=True, help_text='Player age (when DOB not available)', null=True),
        ),
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='reason_for_change',
            field=models.TextField(blank=True, default='', help_text='Reason for change from the uploaded file'),
        ),
        migrations.AddField(
            model_name='bulkplayeruploadrow',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Remarks from the uploaded file'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='age_value',
            field=models.PositiveIntegerField(blank=True, help_text='Player age (used when DOB is not available)', null=True),
        ),
    ]
