# Generated by Django 6.0.2 on 2026-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_bulk_upload_remarks_reason_for_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkplayerupload',
            name='sub_county',
            field=models.CharField(choices=[('Makueni', 'Makueni'), ('Kibwezi West', 'Kibwezi West'), ('Kibwezi East', 'Kibwezi East'), ('Kaiti', 'Kaiti'), ('Kilome', 'Kilome'), ('Mbooni', 'Mbooni')], max_length=100),
        ),
    ]
