# Generated by Django 6.0.2 on 2026-03-31 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0033_alter_player_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkplayerupload',
            name='cso_approved',
            field=models.BooleanField(default=False, help_text='Chief Sports Officer approved'),
        ),
        migrations.AddField(
            model_name='bulkplayerupload',
            name='cso_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkplayerupload',
            name='cso_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads_cso_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkplayerupload',
            name='ds_approved',
            field=models.BooleanField(default=False, help_text='Director Sports approved'),
        ),
        migrations.AddField(
            model_name='bulkplayerupload',
            name='ds_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkplayerupload',
            name='ds_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads_ds_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkplayerupload',
            name='uploaded_by_role',
            field=models.CharField(blank=True, default='', help_text='Role of the user who uploaded (coordinator, chief_sports_officer, etc.)', max_length=30),
        ),
    ]
