# Generated by Django 6.0.2 on 2026-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0035_ligimashinaniregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligimashinaniregistration',
            name='account_created',
            field=models.BooleanField(default=False, help_text='Portal (Team Manager) account auto-created for this manager'),
        ),
        migrations.AlterField(
            model_name='ligimashinaniregistration',
            name='manager_phone',
            field=models.CharField(help_text='WhatsApp-enabled phone number (+254...)', max_length=13),
        ),
        migrations.AlterField(
            model_name='ligimashinaniregistration',
            name='team_name',
            field=models.CharField(help_text='Ward / Ligi Mashinani team name', max_length=200),
        ),
    ]
