# Generated by Django 6.0.2 on 2026-07-06 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_ligi_mashinani_pipeline_models'),
        ('teams', '0036_alter_ligimashinaniregistration_account_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countydiscipline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='countydiscipline',
            name='level',
            field=models.CharField(default='county', help_text='Competition level: ward, subcounty, or county', max_length=20),
        ),
        migrations.AddField(
            model_name='countydiscipline',
            name='ward',
            field=models.CharField(blank=True, default='', help_text='Ward for ward-level competitions', max_length=100),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='source_subcounty_player',
            field=models.ForeignKey(blank=True, help_text='Sub-county player this county player was promoted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_instances', to='teams.countyplayer'),
        ),
        migrations.AddField(
            model_name='countyplayer',
            name='source_ward_player',
            field=models.ForeignKey(blank=True, help_text='Ward player this sub-county player was promoted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcounty_instances', to='teams.countyplayer'),
        ),
        migrations.AddField(
            model_name='countyregistration',
            name='level',
            field=models.CharField(default='county', help_text='Competition level: ward, subcounty, or county', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='qualified_to_county',
            field=models.BooleanField(default=False, help_text='True when this sub-county team has qualified to county finals'),
        ),
        migrations.AddField(
            model_name='team',
            name='qualifying_county_competition',
            field=models.ForeignKey(blank=True, help_text='County competition this team qualified for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualified_teams', to='competitions.competition'),
        ),
        migrations.AlterUniqueTogether(
            name='countydiscipline',
            unique_together={('registration', 'sport_type', 'sub_county', 'level', 'ward')},
        ),
        migrations.CreateModel(
            name='WardLonglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('wscc_approved', 'WSCC Approved'), ('returned', 'Returned for Corrections')], default='draft', help_text='Current status in the WSCC approval workflow', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the longlist was submitted for WSCC review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the WSCC reviewed this longlist', null=True)),
                ('return_reason', models.TextField(blank=True, default='', help_text='Reason provided by WSCC when returning longlist for corrections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.OneToOneField(help_text='Ward discipline this longlist belongs to', limit_choices_to={'level': 'ward'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_longlist', to='teams.countydiscipline')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='WSCC who reviewed this longlist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_longlists_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ward Longlist',
                'verbose_name_plural': 'Ward Longlists',
                'ordering': ['-created_at'],
            },
        ),
    ]
