# Generated by Django 6.0.2 on 2026-07-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0038_ligisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligisettings',
            name='registration_deadline',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='Optional deadline datetime for team registration. Shown as a live countdown on the public homepage. Leave blank to hide the countdown.',
            ),
        ),
    ]
