# Generated by Django 6.0.2 on 2026-07-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0041_wardsubstitutionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countyplayer',
            name='registration_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='System-generated unique registration code (auto-assigned on save for ward players)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When transfer was finalised', null=True),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='from_discipline',
            field=models.ForeignKey(help_text='Source ward discipline (where the player currently plays)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='teams.countydiscipline'),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='player',
            field=models.ForeignKey(help_text='The player being transferred', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='teams.countyplayer'),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Ward TM who submitted this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='scso_notes',
            field=models.TextField(blank=True, default='', help_text='SCSO approval/rejection notes'),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='scso_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='SCSO who gave final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scso_transfer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='to_discipline',
            field=models.ForeignKey(help_text='Destination ward discipline (where the player wants to go)', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='teams.countydiscipline'),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='wscc_notes',
            field=models.TextField(blank=True, default='', help_text='WSCC approval/rejection notes'),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='wscc_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='WSCC who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wscc_transfer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wardsubstitutionrequest',
            name='player_off',
            field=models.ForeignKey(help_text='Ward player coming off', on_delete=django.db.models.deletion.CASCADE, related_name='ward_subbed_off', to='teams.countyplayer'),
        ),
        migrations.AlterField(
            model_name='wardsubstitutionrequest',
            name='player_on',
            field=models.ForeignKey(help_text='Ward player coming on', on_delete=django.db.models.deletion.CASCADE, related_name='ward_subbed_on', to='teams.countyplayer'),
        ),
    ]
