# Generated by Django 6.0.2 on 2026-07-15 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0042_countyplayer_registration_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligitransferrequest',
            name='senior_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ligitransferrequest',
            name='senior_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligitransferrequest',
            name='senior_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='CSO/Director/Admin who reviewed inter-sub-county transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_transfer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligitransferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('within_ward', 'Within Same Ward (Team to Team)'), ('inter_ward', 'Inter-Ward (Same Sub-County)'), ('inter_subcounty', 'Inter-Sub-County'), ('wscc_rejected', 'Rejected by WSCC'), ('scso_approved', 'Approved — Transfer Complete'), ('scso_rejected', 'Rejected by Sub-County Officer'), ('withdrawn', 'Withdrawn by Team Manager')], default='inter_ward', help_text='Auto-computed: within_ward / inter_ward / inter_subcounty', max_length=20),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('wscc_approved', 'WSCC Approved — Pending SCSO'), ('wscc_rejected', 'Rejected by WSCC'), ('scso_approved', 'Approved — Transfer Complete'), ('scso_rejected', 'Rejected by Sub-County Officer'), ('senior_approved', 'Approved by Senior Official'), ('senior_rejected', 'Rejected by Senior Official'), ('withdrawn', 'Withdrawn by Team Manager')], default='pending', max_length=20),
        ),
    ]
