# Generated by Django 4.2.30 on 2026-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0043_transfer_type_senior_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligisettings',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Optional deadline datetime for team registration. Shown as a live countdown on the public homepage. Leave blank to hide the countdown.', null=True),
        ),
    ]
