# Generated by Django 4.2.30 on 2026-07-18 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0044_alter_ligisettings_registration_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRegRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county', models.CharField(help_text='Sub-county this request applies to.', max_length=100)),
                ('action', models.CharField(choices=[('open', 'Open Player Registration'), ('close', 'Close Player Registration')], help_text='Whether to open or close player registration.', max_length=10)),
                ('reason', models.TextField(help_text='Reason for the request (required).')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_note', models.TextField(blank=True, default='', help_text='Optional note from the approver.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(help_text='SCSO who raised the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_reg_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='DS/CSO who approved or rejected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_reg_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Registration Request',
                'verbose_name_plural': 'Player Registration Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
