# Generated by Django 4.2.30 on 2026-07-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0047_subcounty_finals_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('wscc_approved', 'WSCC Approved  -  Pending SCSO'), ('wscc_rejected', 'Rejected by WSCC'), ('scso_approved', 'Approved  -  Transfer Complete'), ('scso_rejected', 'Rejected by Sub-County Officer'), ('senior_approved', 'Approved by Senior Official'), ('senior_rejected', 'Rejected by Senior Official'), ('withdrawn', 'Withdrawn by Team Manager')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ligitransferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('within_ward', 'Within Same Ward (Team to Team)'), ('inter_ward', 'Inter-Ward (Same Sub-County)'), ('inter_subcounty', 'Inter-Sub-County'), ('wscc_rejected', 'Rejected by WSCC'), ('scso_approved', 'Approved  -  Transfer Complete'), ('scso_rejected', 'Rejected by Sub-County Officer'), ('withdrawn', 'Withdrawn by Team Manager')], default='inter_ward', help_text='Auto-computed: within_ward / inter_ward / inter_subcounty', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcountydisciplinecoordinator',
            name='sport_type',
            field=models.CharField(choices=[('football_men', 'Soccer (Men)'), ('football_women', 'Soccer (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball_men', 'Basketball 5x5 (Men)'), ('basketball_women', 'Basketball 5x5 (Women)'), ('basketball_3x3_men', 'Basketball 3x3 (Men)'), ('basketball_3x3_women', 'Basketball 3x3 (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball_men', 'Handball (Men)'), ('handball_women', 'Handball (Women)'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wardallstarsteam',
            name='sport_type',
            field=models.CharField(choices=[('football_men', 'Soccer (Men)'), ('football_women', 'Soccer (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball_men', 'Basketball 5x5 (Men)'), ('basketball_women', 'Basketball 5x5 (Women)'), ('basketball_3x3_men', 'Basketball 3x3 (Men)'), ('basketball_3x3_women', 'Basketball 3x3 (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball_men', 'Handball (Men)'), ('handball_women', 'Handball (Women)'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], max_length=30),
        ),
    ]
