# Generated by Django 6.0.2 on 2026-07-23 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0049_player_removal_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligimashinaniregistration',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='Confirmed by WSCC that the team has paid the required registration fee. Only paid teams can be approved to proceed.'),
        ),
        migrations.AddField(
            model_name='ligimashinaniregistration',
            name='payment_notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes on payment (M-Pesa ref, receipt, etc.)'),
        ),
        migrations.CreateModel(
            name='TeamDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(choices=[('non_participation', 'Non-Participation'), ('duplicate_entry', 'Duplicate Entry'), ('ineligible_team', 'Ineligible Team'), ('non_payment', 'Non-Payment of Registration Fee'), ('other', 'Other (specify in notes)')], default='non_participation', max_length=30)),
                ('reason_detail', models.TextField(help_text="Provide full details justifying this team's removal.")),
                ('status', models.CharField(choices=[('pending_scso', 'Pending SCSO Endorsement'), ('scso_endorsed', 'SCSO Endorsed – Pending CSO Approval'), ('scso_rejected', 'Rejected by SCSO'), ('cso_approved', 'Approved by Chief Sports Officer – Team Deleted'), ('cso_rejected', 'Rejected by Chief Sports Officer')], default='pending_scso', max_length=20)),
                ('scso_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('scso_notes', models.TextField(blank=True, default='')),
                ('cso_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cso_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cso_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_deletion_cso_reviews', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='teams.ligimashinaniregistration')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_deletion_requests_made', to=settings.AUTH_USER_MODEL)),
                ('scso_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_deletion_scso_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Deletion Request',
                'verbose_name_plural': 'Team Deletion Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
