# Generated by Django 6.0.2 on 2026-07-23 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0050_payment_confirmed_and_team_deletion_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdeletionrequest',
            name='director_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teamdeletionrequest',
            name='director_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamdeletionrequest',
            name='director_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_deletion_director_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamdeletionrequest',
            name='status',
            field=models.CharField(choices=[('pending_scso', 'Pending SCSO Endorsement'), ('scso_endorsed', 'SCSO Endorsed – Pending Director of Sports'), ('scso_rejected', 'Rejected by SCSO'), ('director_approved', 'Director Approved – Pending CSO Final Approval'), ('director_rejected', 'Rejected by Director of Sports'), ('cso_approved', 'Approved by Chief Sports Officer – Team Deleted'), ('cso_rejected', 'Rejected by Chief Sports Officer')], default='pending_scso', max_length=20),
        ),
    ]
