# Generated by Django 4.2.30 on 2026-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0051_team_deletion_director_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligimashinaniregistration',
            name='payment_confirmed_by_email',
            field=models.CharField(blank=True, default='', help_text='Email of the user who confirmed payment.', max_length=254),
        ),
        migrations.AddField(
            model_name='ligimashinaniregistration',
            name='payment_confirmed_by_role',
            field=models.CharField(blank=True, default='', help_text='Role of the user who confirmed payment (wscc, admin, etc.)', max_length=40),
        ),
    ]
