# Generated by Django 5.0.4 on 2026-02-26 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('level', models.CharField(choices=[('FIFA', 'FIFA Referee'), ('CAF', 'CAF Referee'), ('National', 'FKF National'), ('County', 'County Level')], default='County', max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, help_text='National ID / Passport', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referees_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referee Profile',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='RefereeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='referee_certs/')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='referees.refereeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RefereeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='referees.refereeprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('referee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RefereeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('centre', 'Centre Referee'), ('ar1', 'Assistant Referee 1'), ('ar2', 'Assistant Referee 2'), ('fourth', '4th Official')], default='centre', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('replaced', 'Replaced')], default='pending', max_length=20)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('appointed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_made', to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_appointments', to='competitions.fixture')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='referees.refereeprofile')),
            ],
            options={
                'ordering': ['-appointed_at'],
                'unique_together': {('fixture', 'referee', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RefereeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('positioning', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('decision_making', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fitness', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('communication', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_reviews', to='competitions.fixture')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='referees.refereeprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'unique_together': {('referee', 'fixture')},
            },
        ),
    ]
