# Generated by Django 6.0.2 on 2026-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Passport-size photo', null=True, upload_to='referee_photos/'),
        ),
    ]
