# Generated by Django 6.0.2 on 2026-03-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_refereeprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeprofile',
            name='referee_type',
            field=models.CharField(choices=[('referee', 'Referee'), ('assistant_referee', 'Assistant Referee')], default='referee', help_text='Whether this official is a Referee or Assistant Referee', max_length=20),
        ),
        migrations.AlterField(
            model_name='refereeappointment',
            name='role',
            field=models.CharField(choices=[('referee', 'Referee'), ('ar1', 'Assistant Referee 1'), ('ar2', 'Assistant Referee 2'), ('reserve', 'Reserve Referee')], default='referee', max_length=20),
        ),
    ]
