# Generated by Django 6.0.2 on 2026-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0003_refereeprofile_referee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeappointment',
            name='role',
            field=models.CharField(choices=[('referee', 'Referee'), ('ar1', 'Assistant Referee 1'), ('ar2', 'Assistant Referee 2'), ('reserve', 'Reserve Referee'), ('first_ref', '1st Referee'), ('second_ref', '2nd Referee'), ('scorer', 'Scorer'), ('line_judge_1', 'Line Judge 1'), ('line_judge_2', 'Line Judge 2'), ('crew_chief', 'Crew Chief'), ('umpire_1', 'Umpire 1'), ('umpire_2', 'Umpire 2'), ('commissioner', 'Commissioner'), ('referee_1', 'Referee 1'), ('referee_2', 'Referee 2'), ('timekeeper', 'Timekeeper'), ('scorekeeper', 'Scorekeeper')], default='referee', max_length=20),
        ),
    ]
