# Generated by Django 6.0.2 on 2026-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0004_alter_refereeappointment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeappointment',
            name='role',
            field=models.CharField(choices=[('referee', 'Referee'), ('ar1', 'Assistant Referee 1 (AR1)'), ('ar2', 'Assistant Referee 2 (AR2)'), ('reserve', 'Reserve Referee (RR)'), ('fourth_official', '4th Official'), ('match_commissioner', 'Match Commissioner'), ('first_ref', '1st Referee'), ('second_ref', '2nd Referee'), ('scorer', 'Scorer'), ('line_judge_1', 'Line Judge 1'), ('line_judge_2', 'Line Judge 2'), ('assistant_scorer', 'Assistant Scorer'), ('line_judge_3', 'Line Judge 3'), ('line_judge_4', 'Line Judge 4'), ('crew_chief', 'Crew Chief'), ('umpire_1', 'Umpire 1'), ('umpire_2', 'Umpire 2'), ('commissioner', 'Commissioner'), ('shot_clock', 'Shot Clock Operator'), ('scorer_bball', 'Scorer'), ('referee_1', 'Referee 1'), ('referee_2', 'Referee 2'), ('timekeeper', 'Timekeeper'), ('scorekeeper', 'Scorekeeper'), ('delegate', 'Delegate')], default='referee', max_length=30),
        ),
    ]
