# Generated by Django 6.0.2 on 2026-03-20 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0006_unique_appointment_role_per_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID', max_length=20, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
    ]
