# Generated by Django 6.0.2 on 2026-03-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0007_alter_refereeprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeprofile',
            name='discipline',
            field=models.CharField(blank=True, default='', help_text='Sport discipline family e.g. football, volleyball, basketball, handball', max_length=30),
        ),
    ]
