# Generated by Django 6.0.2 on 2026-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0008_add_discipline_to_referee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refereeprofile',
            name='years_experience',
        ),
        migrations.AlterField(
            model_name='refereeprofile',
            name='level',
            field=models.CharField(choices=[('FIFA Elite', 'FIFA Elite'), ('FKF Premier League', 'FKF Premier League'), ('FKF National Super League', 'FKF National Super League'), ('FKF Division 1', 'FKF Division 1'), ('Regional', 'Regional'), ('County Grassroot', 'County Grassroot')], default='County Grassroot', max_length=40),
        ),
        migrations.AlterField(
            model_name='refereeprofile',
            name='referee_type',
            field=models.CharField(choices=[('referee', 'Referee'), ('assistant_referee', 'Assistant Referee')], default='referee', help_text='Whether this official is a Referee or Assistant Referee', max_length=20, verbose_name='Specialisation'),
        ),
    ]
