# Generated by Django 6.0.2 on 2026-02-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Competition Manager'), ('referee_manager', 'Referees Manager'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('treasurer', 'Treasurer'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
