# Generated by Django 6.0.2 on 2026-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Competition Manager'), ('referee_manager', 'Referees Manager'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('county_sports_admin', 'County Sports Admin'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
