# Generated by Django 6.0.2 on 2026-03-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_media_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Competition Manager'), ('referee_manager', 'Referees Manager'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('county_sports_admin', 'County Sports Director'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('secretary_general', 'Secretary General'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
