# Generated by Django 6.0.2 on 2026-03-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_discipline',
            field=models.CharField(blank=True, default='', help_text='Sport discipline this coordinator manages (only for Coordinator role)', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Competition Manager'), ('coordinator', 'Discipline Coordinator'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('county_sports_admin', 'County Sports Director'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('secretary_general', 'Secretary General'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
