# Generated by Django 6.0.2 on 2026-03-17 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_assigned_discipline_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_discipline',
            field=models.CharField(blank=True, default='', help_text='Sport discipline this user manages (for Coordinator / Scout roles)', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Organising Secretary'), ('coordinator', 'Discipline Coordinator'), ('verification_officer', 'Verification Officer'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('county_sports_admin', 'County Sports Director'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('secretary_general', 'Secretary General'), ('scout', 'Scout'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
