# Generated by Django 6.0.2 on 2026-03-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_assigned_discipline_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_county',
            field=models.CharField(blank=True, choices=[('Makueni', 'Makueni'), ('Kibwezi West', 'Kibwezi West'), ('Kibwezi East', 'Kibwezi East'), ('Kaiti', 'Kaiti'), ('Kilome', 'Kilome'), ('Mbooni', 'Mbooni')], default='', help_text='Makueni County sub-county (constituency) for sports officers', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Organising Secretary'), ('coordinator', 'Discipline Coordinator'), ('verification_officer', 'Verification Officer'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('county_sports_admin', 'County Sports Director'), ('cec_sports', 'County CEC Member - Sports'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('secretary_general', 'Secretary General'), ('scout', 'Scout'), ('subcounty_sports_officer', 'Sub-County Sports Officer'), ('chief_sports_officer', 'Chief Sports Officer'), ('director_sports', 'Director of Sports'), ('chief_officer_sports', 'Chief Officer - Sports'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
