# Generated by Django 6.0.2 on 2026-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_sub_county_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_discipline',
            field=models.CharField(blank=True, default='', help_text='Sport family or discipline this user manages (for Coordinator / Scout roles)', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_county',
            field=models.CharField(blank=True, default='', help_text='Sub-county or constituency assignment for sub-county sports officers', max_length=100),
        ),
    ]
