# Generated by Django 6.0.2 on 2026-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_assigned_discipline_alter_user_sub_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Organising Secretary'), ('coordinator', 'Discipline Coordinator'), ('verification_officer', 'Verification Officer'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('county_sports_admin', 'Sub-County Sports Director'), ('cec_sports', 'County CEC Member - Sports'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('secretary_general', 'Secretary General'), ('scout', 'Scout'), ('subcounty_sports_officer', 'Sub-County Sports Officer'), ('chief_sports_officer', 'Chief Sports Officer'), ('director_sports', 'Director of Sports'), ('chief_officer_sports', 'Chief Officer - Sports'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
