# Generated by Django 6.0.2 on 2026-03-27 15:57

import django.core.validators
from django.db import migrations, models


def deduplicate_phones(apps, schema_editor):
    """
    Wipe ALL duplicate phone values — every copy gets set to NULL.
    Users with duplicates simply re-enter their phone on next login.
    """
    User = apps.get_model('accounts', 'User')
    from django.db.models import Count

    # 1. Empty strings -> NULL
    User.objects.filter(phone='').update(phone=None)

    # 2. Find every phone that appears more than once and NULL them all
    dupes = (
        User.objects.filter(phone__isnull=False)
        .values('phone')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
        .values_list('phone', flat=True)
    )
    if dupes:
        User.objects.filter(phone__in=list(dupes)).update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_coordinator_display'),
    ]

    operations = [
        # 1. Add id_number field
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number (digits only, 5-10 chars)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
        # 2. First make phone nullable (no unique yet) so we can set NULLs
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
        # 3. Deduplicate: empty strings -> NULL, duplicate phones -> keep latest, NULL rest
        migrations.RunPython(deduplicate_phones, migrations.RunPython.noop),
        # 4. Now apply unique constraint
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
    ]
