# Generated by Django 6.0.2 on 2026-03-27 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_coordinator_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number (digits only, 5-10 chars)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must contain 5 to 10 digits.', regex='^\\d{5,10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX (country code + 9 digits).', regex='^\\+254\\d{9}$')]),
        ),
    ]
