# Generated by Django 6.0.2 on 2026-07-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_phone_unique_add_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.CharField(blank=True, default='', help_text='Ward assignment for ward-level roles such as WSCC and ward team managers', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('competition_manager', 'Organising Secretary'), ('coordinator', 'Coordinator'), ('verification_officer', 'Verification Officer'), ('referee', 'Referee'), ('team_manager', 'Team Manager'), ('cec_sports', 'County CEC Member - Sports'), ('treasurer', 'Treasurer'), ('jury_chair', 'Chair of the Jury'), ('media_manager', 'Media Manager'), ('secretary_general', 'Secretary General'), ('scout', 'Scout'), ('subcounty_sports_officer', 'Sub-County Sports Officer'), ('chief_sports_officer', 'Chief Sports Officer'), ('director_sports', 'Director of Sports'), ('chief_officer_sports', 'Chief Officer - Sports'), ('governor', 'Governor'), ('waziri_sports', 'Waziri - Sports'), ('ward_sports_council_chair', 'Ward Sports Council Chair'), ('admin', 'System Admin')], default='team_manager', max_length=30),
        ),
    ]
