# Generated by Django 4.2.30 on 2026-07-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_ligi_mashinani_pipeline_models'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'ward_sports_council_chair')), fields=('ward', 'sub_county'), name='unique_active_wscc_per_ward_subcounty', violation_error_message='An active Ward Sports Council Chair already exists for this ward in this sub-county. Deactivate the existing account before assigning a new WSCC.'),
        ),
    ]
