# Generated by Django 4.2.7 on 2026-01-13 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('TEAM_CREATE', 'Team Created'), ('TEAM_UPDATE', 'Team Updated'), ('TEAM_DELETE', 'Team Deleted'), ('TEAM_APPROVE', 'Team Approved'), ('TEAM_REJECT', 'Team Rejected'), ('TEAM_SUSPEND', 'Team Suspended'), ('PLAYER_CREATE', 'Player Created'), ('PLAYER_UPDATE', 'Player Updated'), ('PLAYER_DELETE', 'Player Deleted'), ('PLAYER_TRANSFER', 'Player Transfer'), ('MATCH_CREATE', 'Match Created'), ('MATCH_UPDATE', 'Match Updated'), ('MATCH_DELETE', 'Match Deleted'), ('MATCH_RESCHEDULE', 'Match Rescheduled'), ('MATCH_REPORT', 'Match Report Submitted'), ('MATCH_REPORT_APPROVE', 'Match Report Approved'), ('FIXTURE_GENERATE', 'Fixtures Generated'), ('FIXTURE_REGENERATE', 'Fixtures Regenerated'), ('ZONE_ASSIGN', 'Zone Assigned'), ('ZONE_UPDATE', 'Zone Updated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('SUSPENSION_CREATE', 'Suspension Created'), ('SUSPENSION_LIFT', 'Suspension Lifted'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('CONFIG_CHANGE', 'Configuration Changed'), ('REGISTRATION_TOGGLE', 'Registration Window Toggled'), ('OTHER', 'Other Action')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='admin_dashb_timesta_1223ee_idx'), models.Index(fields=['user', '-timestamp'], name='admin_dashb_user_id_b4d50d_idx'), models.Index(fields=['action', '-timestamp'], name='admin_dashb_action_3582d7_idx')],
            },
        ),
    ]
