# Generated by Django 4.2.7 on 2026-01-13 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='can_undo',
            field=models.BooleanField(default=False, help_text='Whether this action can be undone'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_undone',
            field=models.BooleanField(default=False, help_text='Whether this action has been undone'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='new_state',
            field=models.JSONField(blank=True, help_text='State after action', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='previous_state',
            field=models.JSONField(blank=True, help_text='State before action for undo', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='undo_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='undone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
