# Generated by Django 4.2.7 on 2026-01-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_activitylog_can_undo_activitylog_is_undone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changes_json',
            field=models.TextField(blank=True, default='{}', help_text='JSON representation of changes'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('TEAM_CREATE', 'Team Created'), ('TEAM_UPDATE', 'Team Updated'), ('TEAM_DELETE', 'Team Deleted'), ('TEAM_APPROVE', 'Team Approved'), ('TEAM_REJECT', 'Team Rejected'), ('TEAM_SUSPEND', 'Team Suspended'), ('PLAYER_CREATE', 'Player Created'), ('PLAYER_UPDATE', 'Player Updated'), ('PLAYER_DELETE', 'Player Deleted'), ('PLAYER_TRANSFER', 'Player Transfer'), ('MATCH_CREATE', 'Match Created'), ('MATCH_UPDATE', 'Match Updated'), ('MATCH_DELETE', 'Match Deleted'), ('MATCH_RESCHEDULE', 'Match Rescheduled'), ('MATCH_REPORT', 'Match Report Submitted'), ('MATCH_REPORT_APPROVE', 'Match Report Approved'), ('FIXTURE_GENERATE', 'Fixtures Generated'), ('FIXTURE_REGENERATE', 'Fixtures Regenerated'), ('ZONE_ASSIGN', 'Zone Assigned'), ('ZONE_UPDATE', 'Zone Updated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('SUSPENSION_CREATE', 'Suspension Created'), ('SUSPENSION_LIFT', 'Suspension Lifted'), ('MATCHDAY_SQUAD_SUBMIT', 'Matchday Squad Submitted'), ('SQUAD_APPROVE', 'Squad Approved'), ('SQUAD_REJECT', 'Squad Rejected'), ('REFEREE_REGISTER', 'Referee Registered'), ('REFEREE_APPROVE', 'Referee Approved'), ('REFEREE_ACTION', 'Referee Action'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('CONFIG_CHANGE', 'Configuration Changed'), ('REGISTRATION_TOGGLE', 'Registration Window Toggled'), ('ADMIN_ACTION', 'Admin Action'), ('PAYMENT_ACTION', 'Payment Action'), ('OTHER', 'Other Action')], max_length=50),
        ),
    ]
