# Generated by Django 6.0.2 on 2026-03-29 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUT', 'Sent'), ('IN', 'Received')], db_index=True, default='OUT', max_length=3)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('draft', 'Draft')], default='sent', max_length=10)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_emails', models.TextField(help_text='Comma-separated recipient addresses')),
                ('cc_emails', models.TextField(blank=True, default='')),
                ('bcc_emails', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='admin_dashb_sent_at_fcf085_idx'), models.Index(fields=['direction', '-sent_at'], name='admin_dashb_directi_155a29_idx')],
            },
        ),
    ]
