# Generated by Django 6.0.2 on 2026-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='RFC 2822 Message-ID for IMAP dedup', max_length=500),
        ),
    ]
