# Generated by Django 6.0.2 on 2026-03-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0004_countyregistration'),
        ('teams', '0005_add_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief summary of the appeal', max_length=300)),
                ('details', models.TextField(help_text='Full description of the grievance and grounds for appeal')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted — Awaiting Response'), ('response_received', 'Response Received — Awaiting Jury'), ('under_review', 'Under Jury Review'), ('decided', 'Decision Made'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=2000, help_text='Appeal fee in KES', max_digits=10)),
                ('fee_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment Pending Verification'), ('verified', 'Payment Verified'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('fee_reference', models.CharField(blank=True, help_text='M-Pesa or receipt reference for fee payment', max_length=100)),
                ('fee_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_reappeal', models.BooleanField(default=False, help_text='This is a re-appeal of a previously rejected appeal')),
                ('response_deadline', models.DateTimeField(blank=True, help_text='Deadline for respondent team to submit a response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appellant_team', models.ForeignKey(help_text='Team filing the appeal', on_delete=django.db.models.deletion.CASCADE, related_name='appeals_filed', to='teams.team')),
                ('appellant_user', models.ForeignKey(help_text='Team Manager who submitted the appeal', on_delete=django.db.models.deletion.CASCADE, related_name='appeals_submitted', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(blank=True, help_text='Competition this appeal relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='competitions.competition')),
                ('fee_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_fees_verified', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, help_text='Match this appeal relates to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='competitions.fixture')),
                ('original_appeal', models.ForeignKey(blank=True, help_text='Original appeal this re-appeal is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reappeals', to='appeals.appeal')),
                ('respondent_team', models.ForeignKey(help_text='Team the appeal is filed against', on_delete=django.db.models.deletion.CASCADE, related_name='appeals_received', to='teams.team')),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Image / Photo'), ('document', 'Document (PDF / Word)'), ('video', 'Video Evidence'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(help_text='Upload evidence (images, documents, videos)', upload_to='appeals/evidence/%Y/%m/')),
                ('title', models.CharField(help_text='Brief description of this evidence', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this evidence')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='appeals.appeal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appeal Evidence',
                'verbose_name_plural': 'Appeal Evidence Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='Response statement addressing the appeal')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='appeals.appeal')),
                ('respondent_user', models.ForeignKey(help_text='Team Manager who submitted the response', on_delete=django.db.models.deletion.CASCADE, related_name='appeal_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appeal Response',
            },
        ),
        migrations.CreateModel(
            name='JuryDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('successful', 'Appeal Successful'), ('rejected', 'Appeal Rejected'), ('more_info', 'More Information Required')], help_text='Outcome of the appeal', max_length=20)),
                ('reasoning', models.TextField(help_text='Detailed reasoning for the decision — MANDATORY')),
                ('sanctions', models.TextField(blank=True, help_text='Any sanctions or remedies imposed')),
                ('is_published', models.BooleanField(default=False, help_text='When published, both teams can see the decision')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='appeals.appeal')),
                ('decided_by', models.ForeignKey(help_text='Chair of the Jury who made this decision', on_delete=django.db.models.deletion.CASCADE, related_name='jury_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jury Decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Image / Photo'), ('document', 'Document (PDF / Word)'), ('video', 'Video Evidence'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(help_text='Upload evidence supporting the decision', upload_to='appeals/decisions/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='appeals.jurydecision')),
            ],
            options={
                'verbose_name': 'Decision Evidence',
                'verbose_name_plural': 'Decision Evidence Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Image / Photo'), ('document', 'Document (PDF / Word)'), ('video', 'Video Evidence'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(help_text='Upload evidence for the response', upload_to='appeals/responses/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='appeals.appealresponse')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Evidence',
                'verbose_name_plural': 'Response Evidence Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
