# Generated by Django 6.0.2 on 2026-03-04 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField(help_text='Date of the hearing')),
                ('hearing_time', models.TimeField(help_text='Time of the hearing')),
                ('location', models.CharField(blank=True, help_text='Hearing venue or virtual meeting link', max_length=300)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or agenda for the hearing')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal', models.ForeignKey(help_text='Appeal this hearing is for', on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='appeals.appeal')),
                ('scheduled_by', models.ForeignKey(help_text='Jury Chair who scheduled this hearing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hearing Schedule',
                'verbose_name_plural': 'Hearing Schedules',
                'ordering': ['-hearing_date', '-hearing_time'],
            },
        ),
    ]
