# Generated by Django 6.0.2 on 2026-03-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_hearingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='reappeal_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline to file a re-appeal (10 minutes after decision)', null=True),
        ),
    ]
