# Generated by Django 6.0.2 on 2026-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_appeal_reappeal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted - Awaiting Response'), ('response_received', 'Response Received - Awaiting Jury'), ('under_review', 'Under Jury Review'), ('decided', 'Decision Made'), ('closed', 'Closed')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='jurydecision',
            name='reasoning',
            field=models.TextField(help_text='Detailed reasoning for the decision - MANDATORY'),
        ),
    ]
