# Generated by Django 5.0.4 on 2026-02-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='teams.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='teams.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='walkover_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkovers_won', to='teams.team'),
        ),
        migrations.AddField(
            model_name='pool',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='competitions.pool'),
        ),
        migrations.AddField(
            model_name='poolteam',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_teams', to='competitions.pool'),
        ),
        migrations.AddField(
            model_name='poolteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='teams.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='poolteam',
            unique_together={('pool', 'team')},
        ),
    ]
