# Generated by Django 6.0.2 on 2026-02-27 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_sport_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('participation_fee', models.DecimalField(decimal_places=2, default=250000, help_text='Participation fee in KSh (max 250,000)', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa or bank reference number', max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_registrations', to='competitions.competition')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_registrations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'County Registration',
                'verbose_name_plural': 'County Registrations',
                'ordering': ['competition', 'county'],
                'unique_together': {('competition', 'county')},
            },
        ),
    ]
