# Generated by Django 6.0.2 on 2026-03-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_countyregistration'),
        ('teams', '0007_team_away_gk_colour_team_away_kit_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countyregistration',
            name='participation_fee',
        ),
        migrations.RemoveField(
            model_name='countyregistration',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='countyregistration',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='countyregistration',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='competition',
            name='format_type',
            field=models.CharField(choices=[('group_stage', 'Group Stage Only'), ('knockout', 'Knockout Only'), ('group_and_knockout', 'Group Stage + Knockout')], default='group_and_knockout', help_text='Competition format: group stage, knockout, or both', max_length=30),
        ),
        migrations.AddField(
            model_name='competition',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('mixed', 'Mixed')], default='men', help_text='Gender category for this competition', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='qualify_from_group',
            field=models.PositiveIntegerField(default=2, help_text='Number of teams that qualify from each group to knockout'),
        ),
        migrations.AddField(
            model_name='competition',
            name='rules',
            field=models.TextField(blank=True, help_text='Competition rules, regulations, and format details'),
        ),
        migrations.AddField(
            model_name='competition',
            name='teams_per_group',
            field=models.PositiveIntegerField(default=4, help_text='Number of teams per group in group stage'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_penalties',
            field=models.PositiveIntegerField(blank=True, help_text='Away penalty shootout score', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_score_et',
            field=models.PositiveIntegerField(blank=True, help_text='Away score after extra time', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='bracket_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in bracket (1=first match of this round)', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_penalties',
            field=models.PositiveIntegerField(blank=True, help_text='Home penalty shootout score', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_score_et',
            field=models.PositiveIntegerField(blank=True, help_text='Home score after extra time', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='is_knockout',
            field=models.BooleanField(default=False, help_text='Knockout/elimination match'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='knockout_round',
            field=models.CharField(blank=True, choices=[('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarterfinal', 'Quarter-final'), ('semifinal', 'Semi-final'), ('third_place', '3rd Place Play-off'), ('final', 'Final')], default='', help_text='Applicable knockout round (R16, QF, SF, Final)', max_length=20),
        ),
        migrations.AddField(
            model_name='fixture',
            name='leg_number',
            field=models.PositiveIntegerField(blank=True, help_text='Leg number for two-legged ties (1 or 2)', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winner (auto-set or set for knockout ties)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_won', to='teams.team'),
        ),
        migrations.AddField(
            model_name='poolteam',
            name='bonus_points',
            field=models.IntegerField(default=0, help_text='Bonus/penalty points (e.g. deductions)'),
        ),
        migrations.AddField(
            model_name='poolteam',
            name='sets_lost',
            field=models.PositiveIntegerField(default=0, help_text='For volleyball: sets lost'),
        ),
        migrations.AddField(
            model_name='poolteam',
            name='sets_won',
            field=models.PositiveIntegerField(default=0, help_text='For volleyball: sets won'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='sport_type',
            field=models.CharField(choices=[('football_men', 'Football (Men)'), ('football_women', 'Football (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], default='football_men', help_text='Sport discipline for this competition', max_length=30),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('registration', 'Registration Open'), ('upcoming', 'Upcoming'), ('group_stage', 'Group Stage'), ('knockout', 'Knockout Stage'), ('active', 'Active / Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registration', max_length=20),
        ),
        migrations.CreateModel(
            name='CountyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('season', models.CharField(default='2025', max_length=10)),
                ('participation_fee', models.DecimalField(decimal_places=2, default=250000, help_text='Participation fee in KSh (standard 250,000)', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa or bank reference number', max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Treasurer who confirmed the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_payments_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'County Payment',
                'verbose_name_plural': 'County Payments',
                'ordering': ['season', 'county'],
                'unique_together': {('county', 'season')},
            },
        ),
        migrations.AddField(
            model_name='countyregistration',
            name='county_payment',
            field=models.ForeignKey(blank=True, help_text='Link to county-level payment for this season', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='competitions.countypayment'),
        ),
    ]
