# Generated by Django 6.0.2 on 2026-03-19 15:12

from django.db import migrations, models


def zero_existing_county_payments(apps, schema_editor):
    CountyPayment = apps.get_model('competitions', 'CountyPayment')
    CountyPayment.objects.all().update(participation_fee=0)


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_add_basketball_handball_gender_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countypayment',
            name='participation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Participation fee in KSh (MKJ SUPA CUP currently uses 0)', max_digits=10),
        ),
        migrations.RunPython(zero_existing_county_payments, migrations.RunPython.noop),
    ]
