# Generated by Django 6.0.2 on 2026-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_countypayment_participation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='sport_type',
            field=models.CharField(choices=[('football_men', 'Soccer (Men)'), ('football_women', 'Soccer (Women)'), ('volleyball_men', 'Volleyball (Men)'), ('volleyball_women', 'Volleyball (Women)'), ('basketball_men', 'Basketball 5x5 (Men)'), ('basketball_women', 'Basketball 5x5 (Women)'), ('basketball_3x3_men', 'Basketball 3x3 (Men)'), ('basketball_3x3_women', 'Basketball 3x3 (Women)'), ('basketball', 'Basketball'), ('basketball_3x3', 'Basketball 3x3'), ('handball_men', 'Handball (Men)'), ('handball_women', 'Handball (Women)'), ('handball', 'Handball'), ('beach_volleyball', 'Beach Volleyball'), ('beach_handball', 'Beach Handball')], default='football_men', help_text='Sport discipline for this competition', max_length=30),
        ),
    ]
