# Generated by Django 6.0.2 on 2026-03-22 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_competition_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Default venue for fixtures in this pool', null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.venue'),
        ),
    ]
