# Generated by Django 6.0.2 on 2026-03-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_add_venue_to_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countyregistration',
            name='county_payment',
        ),
        migrations.AlterUniqueTogether(
            name='countyregistration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='countyregistration',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='countyregistration',
            name='registered_by',
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('group_stage', 'Group Stage'), ('knockout', 'Knockout Stage'), ('active', 'Active / Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.DeleteModel(
            name='CountyPayment',
        ),
        migrations.DeleteModel(
            name='CountyRegistration',
        ),
    ]
