# Generated by Django 6.0.2 on 2026-03-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_remove_countyregistration_county_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
    ]
