# Generated by Django 6.0.2 on 2026-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_alter_venue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='live_extra_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Added/injury time minutes'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_half',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current half/period (1=1st, 2=2nd, etc.)'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_paused',
            field=models.BooleanField(default=False, help_text='Is the match clock paused (e.g. half-time)'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_started_at',
            field=models.DateTimeField(blank=True, help_text='When the match was kicked off (live)', null=True),
        ),
    ]
