# Generated by Django 6.0.2 on 2026-04-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_fixture_live_extra_minutes_fixture_live_half_and_more'),
        ('teams', '0034_bulk_upload_coordinator_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorer_name', models.CharField(help_text='Name of the goal scorer', max_length=150)),
                ('minute', models.PositiveIntegerField(help_text='Minute the goal was scored (e.g. 45)')),
                ('added_time', models.PositiveIntegerField(default=0, help_text='Added/stoppage time minute (e.g. 3 for 45+3)')),
                ('half', models.PositiveSmallIntegerField(choices=[(1, '1st Half'), (2, '2nd Half'), (3, 'Extra Time 1st'), (4, 'Extra Time 2nd')], default=1)),
                ('goal_type', models.CharField(choices=[('normal', 'Normal'), ('penalty', 'Penalty'), ('free_kick', 'Free Kick'), ('own_goal', 'Own Goal'), ('header', 'Header')], default='normal', max_length=12)),
                ('assist_name', models.CharField(blank=True, default='', help_text='Name of the assisting player', max_length=150)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_goals', to='competitions.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_goals', to='teams.team')),
            ],
            options={
                'ordering': ['half', 'minute', 'added_time'],
            },
        ),
    ]
