# Generated by Django 6.0.2 on 2026-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_add_livegoal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='live_paused_minute',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Frozen match minute when clock is paused', null=True),
        ),
    ]
