# Generated by Django 6.0.2 on 2026-07-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_add_live_paused_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('ward', 'Ward (Ligi Mashinani)'), ('subcounty', 'Sub-County MKJ Finals'), ('county', 'County MKJ Supa Cup')], default='county', help_text='Competition level in the pipeline', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='sub_county',
            field=models.CharField(blank=True, default='', help_text='Makueni sub-county for subcounty/ward competitions', max_length=100),
        ),
        migrations.AddField(
            model_name='competition',
            name='ward',
            field=models.CharField(blank=True, default='', help_text='Ward for ward-level competitions', max_length=100),
        ),
    ]
